imports:
    - { resource: security_dev.yml }
    - { resource: config.yml }
#    - { resource: "@LoginDevBundle/Resources/config/services.yml" }
    - { resource: "@ProyectosBundle/Resources/config/services.yml" }
#    - { resource: "@MantenimientosBundle/Resources/config/services.yml" }
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    group:
        group_class: AppBundle\Entity\Group
    from_email:
        address: "noreply@yourcompany.com"
        sender_name: "No Reply"
    registration:
        form:
            type: AppBundle\Form\RegistrationType

parameters:
    locale: en
    domain: hxnselsymfony.com
    subdomain.portal: www
    subdomain.dash: dash
    app.locales: [en, es]

jms_i18n_routing:
    default_locale: "%locale%"
#    locales: [en, es]
    locales: "%app.locales%"
    strategy: prefix_except_default

framework:
    translator: { fallbacks: ["%locale%"] }
#    default_locale: es
#    translator: ~
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        twig_locales: "%app.locales%"

doctrine:
    dbal:
        driver:   "%database_driver_DEV%"
        host:     "%database_host_DEV%"
        port:     "%database_port_DEV%"
        dbname:   "%database_name_DEV%"
        user:     "%database_user_DEV%"
        password: "%database_password_DEV%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true