_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

ProyectosBundle:
    resource: "@ProyectosBundle/Controller/"
    type:     annotation
    prefix:   /proyectos

#LoginDevBundle:
#    resource: "@LoginDevBundle/Controller/"
#    type:     annotation
#    prefix:   /LoginDevBundle

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
#    prefix:   /inicio
#
AppBundle:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
    host:     "{subdomain}.%domain%"
    requirements:
        subdomain: "%subdomain.portal%|%subdomain.dash%"

DashboardBundle:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard
    host:     "{subdomain}.%domain%"
    defaults:
        subdomain: "%subdomain.dash%"
    requirements:
        subdomain: "%subdomain.dash%"