# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    domain: hxnselsymfony.com
    subdomain.dash: dash

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

#Extensiones del twig(agregar funciones personalizadas)
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
#Servicio personalizado creado para el logueo
    app.form_login_authenticator:
        class: LoginDevBundle\Security\FormLoginAuthenticator
        arguments: ["@router", "@security.password_encoder"]