AppBundle_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods:  GET

AppBundle_generate_orm_to_doctrine:
    path:     /generate-files-to-doctrine/{bundle}
    defaults: { _controller: AppBundle:GenerateToDoctrine:index, bundle: AppBundle }
#    requirements:
#        code: '^[a-zA-Z0-9]{1,20}$'
    methods:  [GET,POST]