AppBundle\Entity\Actividad:
    type: entity
    table: actividad
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                comment: 'Nombre de la actividad que se realizara'
        descripcion:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
                comment: 'Descripcion de la actividad que se realizara'
    lifecycleCallbacks: {  }
