AppBundle\Entity\CategoriaProfesor:
    type: entity
    table: categoria_profesor
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        sueldo:
            type: decimal
            nullable: false
            precision: 6
            scale: 2
        estado:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
