AppBundle\Entity\CierreCaja:
    type: entity
    table: cierre_caja
    indexes:
        fk_cierre_caja_fos_user1_idx:
            columns:
                - fos_user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        fechaRegistro:
            type: datetime
            nullable: false
            options:
                comment: 'fecha de registro de la operacion y/o peticion del cliente'
            column: fecha_registro
        fechaModificacion:
            type: datetime
            nullable: true
            options:
                comment: 'fecha de registro de la operacion y/o peticion del cliente'
            column: fecha_modificacion
        total:
            type: decimal
            nullable: false
            precision: 11
            scale: 2
        estado:
            type: boolean
            nullable: false
            options:
                comment: '1 cierre parcial, 2 cierre caja completo'
    oneToOne:
        fosUser:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fos_user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
