AppBundle\Entity\FosUser:
    type: entity
    table: fos_user
    indexes:
        fk_fos_user_ubigeo1_idx:
            columns:
                - ubigeo_id
    uniqueConstraints:
        UNIQ_957A647992FC23A8:
            columns:
                - username_canonical
        UNIQ_957A6479A0D96FBF:
            columns:
                - email_canonical
        UNIQ_957A6479C05FB297:
            columns:
                - confirmation_token
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        usernameCanonical:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
            column: username_canonical
        email:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        emailCanonical:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
            column: email_canonical
        enabled:
            type: boolean
            nullable: false
        salt:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        confirmationToken:
            type: string
            nullable: true
            length: 180
            options:
                fixed: false
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            column: password_requested_at
        roles:
            type: array
            nullable: false
            length: null
            options:
                fixed: false
        firstName:
            type: string
            nullable: true
            length: 180
            options:
                fixed: false
                comment: Nombre(s)
            column: first_name
        lastName:
            type: string
            nullable: true
            length: 180
            options:
                fixed: false
                comment: Apellido(s)
            column: last_name
        dni:
            type: string
            nullable: true
            length: 7
            options:
                fixed: false
        themeDashboard:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
                comment: 'Tema del dashboard que se le mostrara al usuario'
            column: theme_dashboard
    manyToOne:
        ubigeo:
            targetEntity: Ubigeo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ubigeo_id: { referencedColumnName: id }
            orphanRemoval: false
    manyToMany:
        group:
            targetEntity: FosGroup
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: user
            joinTable:
                name: fos_user_user_group
                joinColumns: [{ name: user_id, referencedColumnName: id }]
                inverseJoinColumns: [{ name: group_id, referencedColumnName: id }]
            orderBy: null
    lifecycleCallbacks: {  }
    repositoryClass: AppBundle\Repository\FosUserRepository
