AppBundle\Entity\Ingresos:
    type: entity
    table: ingresos
    indexes:
        fk_operaciones_cliente_fos_user1_idx:
            columns:
                - fos_user_id
        fk_ingresos_tipo_ingreso_egreso1_idx:
            columns:
                - tipo_ingreso_egreso_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        nombre:
            type: string
            nullable: true
            length: 180
            options:
                fixed: false
        apellidos:
            type: string
            nullable: true
            length: 180
            options:
                fixed: false
        dni:
            type: string
            nullable: true
            length: 7
            options:
                fixed: false
        precio:
            type: decimal
            nullable: false
            precision: 6
            scale: 2
        fechaRegistro:
            type: datetime
            nullable: false
            options:
                comment: 'fecha de registro de la operacion y/o peticion del cliente'
            column: fecha_registro
        fechaModificacion:
            type: datetime
            nullable: true
            options:
                comment: 'fecha de registro de la operacion y/o peticion del cliente'
            column: fecha_modificacion
        estado:
            type: boolean
            nullable: false
            options:
                comment: '1 pendiente, 2 confirmado , 3 anulado'
    oneToOne:
        tipoIngresoEgreso:
            targetEntity: TipoIngresoEgreso
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_ingreso_egreso_id:
                    referencedColumnName: id
            orphanRemoval: false
        fosUser:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fos_user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
