AppBundle\Entity\Membresia:
    type: entity
    table: membresia
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        meses:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Cantidad de meses de la membresia'
        precio:
            type: decimal
            nullable: false
            precision: 6
            scale: 2
        estado:
            type: boolean
            nullable: false
        descripcion:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
    lifecycleCallbacks: {  }
