AppBundle\Entity\Profesor:
    type: entity
    table: profesor
    indexes:
        fk_profesor_categoria_profesor1_idx:
            columns:
                - categoria_profesor_id
        fk_profesor_banco1_idx:
            columns:
                - banco_id
        fk_profesor_ubigeo1_idx:
            columns:
                - ubigeo_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        apellidos:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        dni:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
        direccion:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        telefonoFijo:
            type: string
            nullable: false
            length: 7
            options:
                fixed: false
            column: telefono_fijo
        telefonoMobil:
            type: string
            nullable: true
            length: 9
            options:
                fixed: false
            column: telefono_mobil
        correo:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
        ruc:
            type: string
            nullable: false
            length: 11
            options:
                fixed: false
        numCuenta:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: num_cuenta
    oneToOne:
        banco:
            targetEntity: Banco
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                banco_id:
                    referencedColumnName: id
            orphanRemoval: false
        categoriaProfesor:
            targetEntity: CategoriaProfesor
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                categoria_profesor_id:
                    referencedColumnName: id
            orphanRemoval: false
        ubigeo:
            targetEntity: Ubigeo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ubigeo_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
