AppBundle\Entity\Proveedor:
    type: entity
    table: proveedor
    indexes:
        fk_proveedor_banco1_idx:
            columns:
                - banco_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        nombre:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        direccion:
            type: string
            nullable: false
            length: 500
            options:
                fixed: false
        telefonoFijo1:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
            column: telefono_fijo_1
        telefonoFijo2:
            type: string
            nullable: true
            length: 8
            options:
                fixed: false
            column: telefono_fijo_2
        telefonoMobil:
            type: string
            nullable: true
            length: 9
            options:
                fixed: false
            column: telefono_mobil
        correo:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
        numCuentaBanco:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: num_cuenta_banco
    oneToOne:
        banco:
            targetEntity: Banco
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                banco_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
