AppBundle\Entity\TipoProducto:
    type: entity
    table: tipo_producto
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        descripcion:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
    lifecycleCallbacks: {  }
