AppBundle\Entity\Ubigeo:
    type: entity
    table: ubigeo
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'ID de Ubigeo'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ubivid:
            type: string
            nullable: false
            length: 6
            options:
                fixed: true
                comment: 'ID de Ubigeo'
        ubivdescrip:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                comment: Descripción
        ubivdescripcompleta:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
                comment: 'Descripción completa'
        ubicestado:
            type: string
            nullable: false
            length: 1
            options:
                fixed: true
                comment: 'Estado: (1): Activo,(0):Inactivo'
    lifecycleCallbacks: {  }
    repositoryClass: AppBundle\Repository\UbigeoRepository
