# src/AppBundle/Resources/config/doctrine/User.orm.yml
#AppBundle\Entity\User:
#    type:  entity
#    table: fos_user
#    id:
#        id:
#            type: integer
#            generator:
#                strategy: AUTO
# src/AppBundle/Resources/config/doctrine/User.orm.yml
AppBundle\Entity\User:
    type:  entity
    table: fos_user
    indexes:
        fk_fos_user_ubigeo1_idx:
            columns:
                - ubigeo_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: true
            length: 180
            options:
                fixed: false
                comment: Nombre(s)
            column: first_name
        lastName:
            type: string
            nullable: true
            length: 180
            options:
                fixed: false
                comment: Apellido(s)
            column: last_name
        dni:
            type: string
            nullable: true
            length: 7
            options:
                fixed: false
        themeDashboard:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
                comment: 'Tema del dashboard que se le mostrara al usuario'
            column: theme_dashboard
    manyToOne:
        ubigeo:
            targetEntity: Ubigeo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ubigeo_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        groups:
            targetEntity: Group
            joinTable:
                name: fos_user_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id