# src/AppBundle/Resources/config/doctrine/User.orm.yml
#AppBundle\Entity\User:
#    type:  entity
#    table: fos_user
#    id:
#        id:
#            type: integer
#            generator:
#                strategy: AUTO
# src/AppBundle/Resources/config/doctrine/User.orm.yml
AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToMany:
        groups:
            targetEntity: Group
            joinTable:
                name: fos_user_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id