# src/AppBundle/Resources/config/doctrine/User.orm.yml
#AppBundle\Entity\User:
#    type:  entity
#    table: fos_user
#    id:
#        id:
#            type: integer
#            generator:
#                strategy: AUTO
# src/AppBundle/Resources/config/doctrine/User.orm.yml
AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            nullable: true
            length: 180
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: true
            length: 180
            options:
                fixed: false
            column: last_name
        themeDashboard:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: theme_dashboard
    manyToMany:
        groups:
            targetEntity: Group
            joinTable:
                name: fos_user_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id